### ISSUE TITLE
能启动服务，但提交就报500错误，docker或本地部署都是这样

### ISSUE THREAD

**Issue by lauweliam** [erictik/midjourney-ui#38]
报错信息如下 ：
- error Error: The edge runtime does not support Node.js 'http' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime
    at <unknown> (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:33)
    at Object.get (webpack-internal:///(middleware)/./node_modules/next/dist/esm/server/web/globals.js:33:19)
    at eval (webpack-internal:///(middleware)/./node_modules/agent-base/dist/index.js:45:26)
    at (middleware)/./node_modules/agent-base/dist/index.js (file:///Users/weliam/study/midjourney-ui/.next/server/pages/api/imagine.js:140:1)
    at __webpack_require__ (file:///Users/weliam/study/midjourney-ui/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///Users/weliam/study/midjourney-ui/.next/server/edge-runtime-webpack.js:268:21)
    at eval (webpack-internal:///(middleware)/./node_modules/https-proxy-agent/dist/index.js:49:22)
    at (middleware)/./node_modules/https-proxy-agent/dist/index.js (file:///Users/weliam/study/midjourney-ui/.next/server/pages/api/imagine.js:184:1)
    at __webpack_require__ (file:///Users/weliam/study/midjourney-ui/.next/server/edge-runtime-webpack.js:37:33)
    at fn (file:///Users/weliam/study/midjourney-ui/.next/server/edge-runtime-webpack.js:268:21)
    at eval (webpack-internal:///(middleware)/./node_modules/midjourney/libs/midjourne.api.js:10:29) {
  digest: undefined
}

请问这问题如何解决？

**Comment by zcpua** [comment]
yarn add midjourney
https://github.com/erictik/midjourney-ui/commit/67a10c303ce773a1bbba1880ff00daa39839b85d

**Comment by APPX-Studio** [comment]
可以用啊 我没做二次开发，就是不能支持 描述 blender浑图模式
