### ISSUE TITLE
docker run 1.1.47 with error

### ISSUE THREAD

**Issue by lehug** [erictik/midjourney-ui#59]
```
Digest: sha256:66f1dd266b4a1e4b3c0409b7f27ab5039e6166a2da40c97f87e8c19958269046
Status: Downloaded newer image for erictik/midjourney-ui:latest
yarn run v1.22.19
$ next start
  ▲ Next.js 13.5.3
  - Local:        http://localhost:3000

 ✓ Ready in 582ms
Error: Cannot find module 'next/dist/shared/lib/html-context.js'
Require stack:
- /dist/.next/server/pages/_document.js
- /dist/node_modules/next/dist/server/require.js
- /dist/node_modules/next/dist/server/next-server.js
- /dist/node_modules/next/dist/server/next.js
- /dist/node_modules/next/dist/server/lib/start-server.js
- /dist/node_modules/next/dist/cli/next-start.js
- /dist/node_modules/next/dist/lib/commands.js
- /dist/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /dist/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/dist/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:130:18)
    at 8743 (/dist/.next/server/pages/_document.js:263:18)
    at __webpack_require__ (/dist/.next/server/webpack-runtime.js:25:42)
    at 2940 (/dist/.next/server/chunks/378.js:6354:22)
    at __webpack_require__ (/dist/.next/server/webpack-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dist/.next/server/pages/_document.js',
    '/dist/node_modules/next/dist/server/require.js',
    '/dist/node_modules/next/dist/server/next-server.js',
    '/dist/node_modules/next/dist/server/next.js',
    '/dist/node_modules/next/dist/server/lib/start-server.js',
    '/dist/node_modules/next/dist/cli/next-start.js',
    '/dist/node_modules/next/dist/lib/commands.js',
    '/dist/node_modules/next/dist/bin/next'
  ]
}
Error: Cannot find module 'next/dist/shared/lib/html-context.js'
Require stack:
- /dist/.next/server/pages/_document.js
- /dist/node_modules/next/dist/server/require.js
- /dist/node_modules/next/dist/server/next-server.js
- /dist/node_modules/next/dist/server/next.js
- /dist/node_modules/next/dist/server/lib/start-server.js
- /dist/node_modules/next/dist/cli/next-start.js
- /dist/node_modules/next/dist/lib/commands.js
- /dist/node_modules/next/dist/bin/next
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /dist/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/dist/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:130:18)
    at 8743 (/dist/.next/server/pages/_document.js:263:18)
    at __webpack_require__ (/dist/.next/server/webpack-runtime.js:25:42)
    at 2940 (/dist/.next/server/chunks/378.js:6354:22)
    at __webpack_require__ (/dist/.next/server/webpack-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/dist/.next/server/pages/_document.js',
    '/dist/node_modules/next/dist/server/require.js',
    '/dist/node_modules/next/dist/server/next-server.js',
    '/dist/node_modules/next/dist/server/next.js',
    '/dist/node_modules/next/dist/server/lib/start-server.js',
    '/dist/node_modules/next/dist/cli/next-start.js',
    '/dist/node_modules/next/dist/lib/commands.js',
    '/dist/node_modules/next/dist/bin/next'
  ]
}
```

**Comment by ruihanma** [comment]
same to me. any solution?

**Comment by bvzgame** [comment]
> same to me. any solution?

for anyone still having issues with this repo - i found someone that forked it and it works! shoutout @SoyZhou 
https://github.com/SoyZhou/midjourney-ui

**Comment by zmrbak** [comment]
same to me.

yarn run v1.22.19
$ next start
  ▲ Next.js 13.5.3
  - Local:        http://localhost:3000

 ✓ Ready in 308ms
Error: Cannot find module 'next/dist/shared/lib/html-context.js'
Require stack:
- /dist/.next/server/pages/_document.js
- /dist/node_modules/next/dist/server/require.js
- /dist/node_modules/next/dist/server/next-server.js
- /dist/node_modules/next/dist/server/next.js
- /dist/node_modules/next/dist/server/lib/start-server.js
- /dist/node_modules/next/dist/cli/next-start.js
- /dist/node_modules/next/dist/lib/commands.js
- /dist/node_modules/next/dist/bin/next
- ...................
